/**
 * Types for the FishingSpots (Locations) feature.
 * These are frontend-facing interfaces derived from the PayloadCMS collection.
 */

export interface FishingSpotCoordinates {
  latitude: number;
  longitude: number;
}

/**
 * Environmental / weather data group (mirrors the `environmentalData`
 * group field in the FishingSpots Payload collection).
 */
export interface FishingSpotEnvironmentalData {
  /** Water temperature in °C */
  waterTemp?: number | null;
  /** Air temperature in °C */
  airTemp?: number | null;
  /** Atmospheric pressure in hPa */
  pressure?: number | null;
  /** Wind speed in km/h */
  windSpeed?: number | null;
  /** Best fishing hours (e.g. "05:00 – 09:00") */
  bestHours?: string | null;
}

/**
 * Represents a fishing spot as stored/returned by Payload CMS.
 * The `id` is auto-generated by Payload.
 */
export interface FishingSpot {
  id: string;
  /** Localized location name */
  name: string;
  /** Short description / fishing opportunities (localized) */
  description?: string | null;
  /** Geographic coordinates for the map marker */
  coordinates: FishingSpotCoordinates;
  /** Water body type */
  waterBodyType?: "lake" | "river" | "reservoir" | null;
  /** Administrative region (voivodeship) */
  region?: string | null;
  /** Bite chance percentage 0–100 (updated by AI/weather job) */
  biteChance?: number | null;
  /**
   * Environmental data group (weather-job populated).
   * Mirrors the `environmentalData` group field in FishingSpots collection.
   */
  environmentalData?: FishingSpotEnvironmentalData | null;
  /** PZW Zone / District information */
  pzwZone?: {
    id: string;
    name: string;
    region?: string | null;
    rules?: any | null;
    permitsRequired?: string | null;
  } | null;
  /** Related fish species names (populated from relationship) */
  species?: string[];
  createdAt: string;
  updatedAt: string;
}

/**
 * Props for the PolandMap component.
 */
export interface PolandMapProps {
  /** Fishing spots fetched from CMS to render as markers */
  spots: FishingSpot[];
  /** Currently selected spot ID (controlled from parent) */
  selectedSpotId?: string | null;
  /** Callback when a marker is clicked */
  onSpotSelect: (spot: FishingSpot | null) => void;
}
